---
- name: Debian | Install prerequisite packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ prereq_pkgs }}"

- name: Debian | Install docker apt repo keyring
  ansible.builtin.apt_key:
    url: "{{ docker_keyring.url }}"
    keyring: "{{ docker_keyring.file }}"
    state: present
  become: true

- name: Debian | Add docker apt repository
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
    mode: "0644"
    filename: "{{ item.filename }}"
    update_cache: true
    validate_certs: true
  become: true
  loop: "{{ docker_repos }}"

- name: Debian | Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ packages }}"
...
