galaxy_info:
  namespace: iorchard
  role_name: keepalived
  author: "Heechul Kim <jijisa@iorchard.net>"
  description: Ansible Role to Install Keepalived for openldap
  company: iOrchard, Inc.
  license: Apache-2.0
  min_ansible_version: "2.11"
  platforms:
    - name: Debian
      versions:
        - bullseye
  galaxy_tags:
    - system

dependencies: []
